### PR TITLE
WIP: Update model at runtime

### PR DESCRIPTION
**Pull request by bakwc**
Ability to add text fragments to a model in runtime, relates to #18

### CODE REVIEW

**Comment by iosadchiy** [comment]
A very useful feature. Is there any chance to see it merged?

Also I don't quite understand how it updates the perfect hash: if the text fragment to be added contains an n-gram that is not present in the hash, how to add it? Don't you have to re-calculate perfect hash from scratch?

**Comment by bakwc** [comment]
> A very useful feature. Is there any chance to see it merged?

I'll try to continue working on this, but not sure when.

> Also I don't quite understand how it updates the perfect hash: if the text fragment to be added contains an n-gram that is not present in the hash, how to add it? Don't you have to re-calculate perfect hash from scratch?

I planed to add a separate hash_table for additional words, it would be ok only for adding small amount of new words / sentences at runtime. For example in text editors when you plan to add some exceptions / ignore some errors.

**Comment by iosadchiy** [comment]
Actually, what I'm trying to do is to first create the model based on n-gram frequencies (#31) and then update it with some domain-specific texts. What could be the best approach here?

It seems like the functionality from this PR is not the best choice (due to the use of an additional hash table).

The other approach is to store all the ngrams in the model (without loading them into memory). This should allow to re-train the model on additional data.

Maybe you'll suggest something better?

**Comment by bakwc** [comment]
> The other approach is to store all the ngrams in the model (without loading them into memory). This should allow to re-train the model on additional data.

It could lead to a performance issues if we will go to disk each time we need to get frequency.

**Comment by Jbiloki** [comment]
Is there a main function to invoke these commands?

**Comment by rprilepskiy** [comment]
@bakwc, do you (by any chance) have plans to solve the conflicts?

**Comment by bakwc** [comment]
sory, currently have no time (

**Comment by bakwc** [comment]
Done in `Pro` version.

JamSpellPro is available at [jamspell.com](https://jamspell.com)

**Pull request closed without merging**
